ControleDeEstoque/Models/GrupoProdutoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ControleDeEstoque.Models
{
    public class GrupoProdutoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
    }
}

ControleDeEstoque/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleDeEstoque.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage ="Informe o usuário")]
        [Display(Name ="Usuário")]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [Display(Name = "Lembrar me")]
        public bool LembrarMe { get; set; }

        
    }
}

ControleDeEstoque/Models/UsuarioModel.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace ControleDeEstoque.Models
{
    public class UsuarioModel
    {
        public static bool ValidarUsuario(string login, string senha)
        {
            var ret = false;
            using (var conexao = new SqlConnection())
            {
                conexao.ConnectionString = "Data Source=DESKTOP-KI43LUD\\SQLEXPRESS; initial Catalog=controleEstoque; User id=sa; Password=eliezer140393;";
                conexao.Open();
                using (var comando = new SqlCommand())
                {
                    comando.Connection = conexao;
                    comando.CommandText = string.Format("select count(*) from TB_Login where NM_Login = '{0}' and NM_Senha = '{1}'",login,senha);
                    ret = ((int)comando.ExecuteScalar() > 0);
                }
            }
            return ret;
        }

    }
}

ControleDeEstoque/Controllers/CadastroController.cs
using ControleDeEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class CadastroController : Controller
    {
        public static List<GrupoProdutoModel> _listaGrupoProdutos = new List<GrupoProdutoModel>()
        {
            new GrupoProdutoModel() { Id=1, Nome="Livros", Ativo = true},
        new GrupoProdutoModel() { Id = 2, Nome = "Mouses", Ativo = true},
        new GrupoProdutoModel() { Id = 3, Nome = "Monitores", Ativo = false}

        };
        // GET: Cadastro
        [Authorize]
        public ActionResult GrupoProduto()
        {
            return View(_listaGrupoProdutos);
        }
        [HttpPost]
        [Authorize]
        public ActionResult RecuperarGrupoProduto(int id)
        {
            return Json(_listaGrupoProdutos.Find(x => x.Id == id));
        }

        [HttpPost]
        [Authorize]
        public ActionResult SalvarGrupoProduto(GrupoProdutoModel model)
        {
            var registroBD = _listaGrupoProdutos.Find(x => x.Id == model.Id);
            if(registroBD == null)
            {
                registroBD = model;
                registroBD.Id = _listaGrupoProdutos.Max(x => x.Id) + 1;
                _listaGrupoProdutos.Add(registroBD);
            }
            else
            {
                registroBD.Nome = model.Nome;
                registroBD.Ativo = model.Ativo;
            }
            return Json(registroBD);
        }
        [HttpPost]
        [Authorize]
        public ActionResult ExcluirGrupoProduto(int id)
        {
            var ret = false;

          var registroBD = _listaGrupoProdutos.Find(x => x.Id == id);
            if(registroBD != null)
            {
                _listaGrupoProdutos.Remove(registroBD);
                ret = true;
            }
            return Json(ret);
        }

        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }
        [Authorize]

        public ActionResult LocalProduto()
        {
            return View();
        }
        [Authorize]

        public ActionResult UnidadeMedida()
        {
            return View();
        }
        [Authorize]

        public ActionResult Produto()
        {
            return View();
        }
        [Authorize]

        public ActionResult Pais()
        {
            return View();
        }
        [Authorize]

        public ActionResult Estado()
        {
            return View();
        }
        [Authorize]

        public ActionResult Cidade()
        {
            return View();
        }
        [Authorize]

        public ActionResult Fornecedor()
        {
            return View();
        }
        [Authorize]

        public ActionResult PerfilUsuario()
        {
            return View();
        }
        [Authorize]

        public ActionResult Usuario()
        {
            return View();
        }

    }
}

ControleDeEstoque/Controllers/ContaController.cs
using ControleDeEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.ModelBinding;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleDeEstoque.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]

        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(login);

            }
            var achou = (UsuarioModel.ValidarUsuario(login.Usuario,login.Senha));
            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);
                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                RedirectToAction("index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login invalido.");

            }

            return View(login);
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Logoff()
        {
            FormsAuthentication.SignOut();
           return RedirectToAction("index", "Home");
        }
    }

}

ControleDeEstoque/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        [Authorize]

        public ActionResult PerdasMes()
        {
            return View();
        }
        [Authorize]

        public ActionResult EntradaSaidaMes()
        {
            return View();
        }
    }
}

ControleDeEstoque/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]

        public ActionResult Index()
        {
            return View();
        }
        [Authorize]

        public ActionResult Sobre()
        {

            return View();
        }


    }
}

ControleDeEstoque/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class OperacaoController : Controller
    {
        // GET: Operacao
        [Authorize]

        public ActionResult EntradaEstoque()
        {
            return View();
        }
        [Authorize]

        public ActionResult SaidaEstoque()
        {
            return View();
        }
        [Authorize]

        public ActionResult LancPerdaProduto()
        {
            return View();
        }
        [Authorize]

        public ActionResult Inventario()
        {
            return View();
        }
    }
}

ControleDeEstoque/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: Relatorio
        [Authorize]

        public ActionResult PosicaoEstoque()
        {
            return View();
        }
        [Authorize]

        public ActionResult Ressuprimento()
        {
            return View();
        }
   
    }
}

ControleDeEstoque/Views/Cadastro/Cidade.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/Estado.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/Fornecedor.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/GrupoProduto.cshtml
@model List<ControleDeEstoque.Models.GrupoProdutoModel>

@{
    ViewBag.Title = "Cadastro de Grupo de produtos";
}
<style>
    #cabecalho_grid > thead > tr th:nth-child(2) {
        width: 110px;
    }

    #cabecalho_grid > thead > tr th:nth-child(3) {
        width: 200px;
    }

    #cadastro {
        width: 70%;
        margin: 0 auto;
    }

    #cadastro_cabecalho {
        border-bottom: 1px #dddddd solid;
    }

    #cadastro_conteudo {
        margin-top: 20px;
    }

    #cabecalho_grid {
        margin-bottom: 20px;
    }
</style>

<div id="cadastro">
    <section id="cadastro_cabecalho">
        <h1>@ViewBag.Title</h1>
    </section>
    <section id="cadastro_conteudo">

        <div id="cabecalho_grid" class="row">
            <div class="col-md-12">
                <a id="btn_incluir" class="btn btn-success" role="button"> <i class="glyphicon glyphicon-plus"></i>Incluir</a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table id="grid-cadastro" class="table table-bordered table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Ativo</th>
                            <th>Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr data-id="@item.Id">
                                <td>@item.Nome</td>

                                <td>@{var ativo = (item.Ativo ? "SIM" : "NÄO"); }@ativo</td>
                                <td>
                                    <a class="btn btn-primary btn-alterar" role="button"> <i class="glyphicon glyphicon-pencil"></i>Alterar</a>
                                    <a class="btn btn-danger btn-excluir" role="button"> <i class="glyphicon glyphicon-trash"></i>Excluir</a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>
@Html.Hidden("id_cadastro")
<div id="modal_cadastro" class="form-horizontal invisivel" role="dialog">
    <fieldset>
        <div class="row">
            <div class="form-group">
                <div class="col-md-12">
                    @Html.Label("txt_nome", "Nome", new { @class = "col-md-3 control-label" })

                    @Html.TextBox("txt_nome", null, new { @class = "form-control" })

                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    @Html.Label("cbx_ativo", "Ativo", new { @class = "col-md-3 control-label" })

                    @Html.CheckBox("cbx_ativo")
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="modal-footer">
                        <a id="btn-sair" class="btn btn-default" role="button" data-dismiss="modal"><i class="glyphicon glyphicon-remove"></i> Sair</a>
                        <a id="btn-confirmar" class="btn btn-primary" role="button"><i class="glyphicon glyphicon-ok"></i> Salvar</a>

                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</div>
@section Scripts{
    <script>
        function abrir_form(dados) {
            $('#id_cadastro').val(dados.Id);
            $('#txt_nome').val(dados.Nome);
            $('#cbx_ativo').prop('checked', dados.Ativo);
              var modal = $('#modal_cadastro');
            bootbox.dialog({
                title: '@ViewBag.Title',
                message:modal
            })
                .on('shown.bs.modal', function () {
                    modal.show(0, function () {
                        $('#txt_nome').focus();
                    });
                      })
                .on('hidden.bs.modal', function () {
                    modal.hide().appendTo('body')
                });

        }
        function criar_linha_grid(dados) {
            var ret =
                    '<tr data-id=' + dados.Id + '>' +
                    '<td>' + dados.Nome + '</td>' +
                    '<td>' + (dados.Ativo ? 'SIM' : 'NÄO') + '</td>' +
                    '<td>' +
                    '<a class="btn btn-primary btn-alterar" role="button" style="margin-right: 3px"> <i class="glyphicon glyphicon-pencil"></i>Alterar</a>' +
                    '<a class="btn btn-danger btn-excluir" role="button"> <i class="glyphicon glyphicon-trash"></i>Excluir</a>' +
                    '</td>' +
                    '</tr>';
            return ret;
        }
        $(document).on('click', '#btn_incluir', function () {
            abrir_form({ Id: 0, Nome: '', Ativo: true });
        })
            .on('click', '.btn-alterar', function () {
                var btn = $(this),
                    id = btn.closest('tr').attr('data-id'),
                    url = '@Url.Action("RecuperarGrupoProduto", "Cadastro")',
                    param = { 'id': id };
                $.post(url, param, function (response) {
                    if (response) {
                        abrir_form(response);
                    }
                });

            })
            .on('click', '.btn-excluir', function () {
                var btn = $(this),
                    tr = btn.closest('tr'),
                    id = tr.attr('data-id'),
                    url = '@Url.Action("ExcluirGrupoProduto", "Cadastro")',
                    param = { 'id': id };

                bootbox.confirm({
                    message: "Realmente deseja excluir o produto ?",
                    buttons: {
                        confirm: {
                            label: 'Sim',
                            className: 'btn-success'
                        },
                        cancel: {
                            label: 'Não',
                            className: 'btn-danger'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $.post(url, param, function (response) {
                                if (response) {
                                    tr.remove();
                                }
                            });
                        }
                    }
                });

            })
            .on('click', '#btn-confirmar', function () {
                 var btn = $(this),
                    url = '@Url.Action("SalvarGrupoProduto", "Cadastro")',
                     param = {
                         Id: $('#id_cadastro').val(),
                         Nome: $('#txt_nome').val(),
                         Ativo: $('#cbx_ativo').prop('checked')
                     };
                $.post(url, param, function (response) {
                    if (response) {

                        if (param.Id == 0) {
                            var table = $('#grid-cadastro').find('tbody'),
                                linha = criar_linha_grid(response);

                            table.append(linha);
                        }
                        else {
                            var linha = $('#grid-cadastro').find('tr[data-id=' + param.Id + ']').find('td');
                            linha
                                .eq(0).html(param.Nome).end()
                                .eq(1).html(param.Ativo ? 'SIM' : 'NÃO');
                        }


                        $('#modal_cadastro').parents('.bootbox').modal('hide');
                    }
                });
            });
    </script>
}

ControleDeEstoque/Views/Cadastro/LocalProduto.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/MarcaProduto.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/Pais.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/PerfilUsuario.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/Produto.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/UnidadeMedida.cshtml
@{
    ViewBag.Title = "GrupoProduto";
}

<h2>GrupoProduto</h2>

ControleDeEstoque/Views/Cadastro/Usuario.cshtml
@{
    ViewBag.Title = "Usuario";
}

<h2>Usuario</h2>

ControleDeEstoque/Views/Conta/Login.cshtml
@model ControleDeEstoque.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<div class="container-login">
    <div class="row">
        <h3 class="titulo"> Entrar no sistema</h3>

    </div>
    <div class="row">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Usuario, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        @Html.CheckBoxFor(m => m.LembrarMe)
                        @Html.LabelFor(m => m.LembrarMe)

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2">
                        <input type="submit" class="btn btn-success" value="Entrar" />
                    </div>
                </div>
            }
        </section>

    </div>

</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval"); 
      }

ControleDeEstoque/Views/Grafico/EntradaSaidaMes.cshtml
@{
    ViewBag.Title = "EntradaSaidaMes";
}

<h2>EntradaSaidaMes</h2>

ControleDeEstoque/Views/Grafico/PerdasMes.cshtml
@{
    ViewBag.Title = "PerdasMes";
}

<h2>PerdasMes</h2>

ControleDeEstoque/Views/Home/Sobre.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title Controle de estoque</h2>

ControleDeEstoque/Views/Operacao/EntradaEstoque.cshtml
@{
    ViewBag.Title = "EntradaEstoque";
}

<h2>EntradaEstoque</h2>

ControleDeEstoque/Views/Operacao/Inventario.cshtml
@{
    ViewBag.Title = "EntradaEstoque";
}

<h2>EntradaEstoque</h2>

ControleDeEstoque/Views/Operacao/LancPerdaProduto.cshtml
@{
    ViewBag.Title = "EntradaEstoque";
}

<h2>EntradaEstoque</h2>

ControleDeEstoque/Views/Operacao/SaidaEstoque.cshtml
@{
    ViewBag.Title = "EntradaEstoque";
}

<h2>EntradaEstoque</h2>

ControleDeEstoque/Views/Relatorio/PosicaoEstoque.cshtml
@{
    ViewBag.Title = "PosicaoEstoque";
}

<h2>PosicaoEstoque</h2>

ControleDeEstoque/Views/Relatorio/Ressuprimento.cshtml
@{
    ViewBag.Title = "Ressuprimento";
}

<h2>Ressuprimento</h2>

ControleDeEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de estoque </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastros
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupo de produtos", "GrupoProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Marcas de produtos", "MarcaProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Locais de armazenamento", "LocalProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de medida", "UnidadeMedida", "Cadastro")</li>
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li class="nav-divider"></li>

                                <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                                <li>@Html.ActionLink("Perfis de Usuário", "PerfilUsuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de produtos", "EntradaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Saida de produtos", "SaidaEstoque", "Operacao")</li>
                                <li>@Html.ActionLink("Lançamento de perda de produtos", "LancPerdaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Inventário de estoque", "Inventario", "Operacao")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatórios
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">

                                <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Perdas por mês", "PerdasMes", "Grafico")</li>
                                <li>@Html.ActionLink("Entradas vs saídas por mês", "EntradaSaidaMes", "Grafico")</li>

                            </ul>
                        </li>
                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "logoffForm" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#"> Olá @User.Identity.Name</a></li>

                            <li><a href="javascript:document.getElementById('logoffForm').submit()"> Sair </a></li>
                        </ul>
                    }

                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>